package enhancedportals.utility;

public class GuiEnums
{
    public enum GUI_DIAL {
        DIAL_A, DIAL_B, DIAL_C, DIAL_D, DIAL_E, ADDRESS_DIAL
    }

    public enum GUI_ADDRESS_BOOK {
        ADDRESS_BOOK_A, ADDRESS_BOOK_B, ADDRESS_BOOK_C, ADDRESS_BOOK_D, ADDRESS_BOOK_E
    }

    public enum GUI_CONTROLLER {
        CONTROLLER_A, CONTROLLER_B
    }

    public enum GUI_TEXTURE {
        TEXTURE_A, TEXTURE_B, TEXTURE_C, TEXTURE_DIAL_EDIT_A, TEXTURE_DIAL_EDIT_B, TEXTURE_DIAL_EDIT_C, TEXTURE_DIAL_SAVE_A, TEXTURE_DIAL_SAVE_B, TEXTURE_DIAL_SAVE_C
    }

    public enum GUI_TRANFER {
        TRANSFER_FLUID, TRANSFER_ENERGY, TRANSFER_ITEM
    }

    public enum GUI_MISC {
        DIM_BRIDGE_STABILIZER, REDSTONE_INTERFACE, MODULE_MANIPULATOR, NETWORK_INTERFACE_A, NETWORK_INTERFACE_B
    }
}